### PR TITLE
REG-275 styling switch

### PR DESCRIPTION
**Pull request by tveronezi**
screen shot 2016-10-25 at 10 59 34 am
screen shot 2016-10-25 at 10 59 43 am
screen shot 2016-10-25 at 10 59 48 am

### CODE REVIEW

**Comment by jeanouii** [comment]
retest this please

**Comment by jeanouii** [comment]
retest this please

**Comment by jeanouii** [comment]
@tbookless there is a JIRA to support more than one authentication mean and create the style. Ryan did the style and Thiago is implementing.

As per the full width, it is on iphone6 ;-)

**Comment by tbookless** [comment]
are the style issues in another PR? @jeanouii

**Comment by jeanouii** [comment]
@tbookless  The title of the JIRA is "UI - support 2 authentication mechanisms"
And the description says it needs a switch.

I can clarify it, but this is the right one.

**Comment by tbookless** [comment]
I added a comment but my point is that the Jira should state info there is a change like this because it reads like a backend change to me.

**Pull request merged**
