### PR TITLE
REG-138 text field valid values

### PR DESCRIPTION
**Pull request by tveronezi**

### CODE REVIEW

**Comment by tveronezi** [comment]
screen shot 2016-10-24 at 5 22 20 pm

**Comment by jeanouii** [comment]
See comment on the JIRA. Basically it looks ok at first glance but the validation rules need to be explicitly defined.

**Comment by tveronezi** [comment]
screen shot 2016-10-27 at 11 25 49 am

**Comment by tveronezi** [comment]
screen shot 2016-10-27 at 1 16 29 pm

**Comment by jeanouii** [comment]
@tveronezi why would query parameters be not valid?
for instance ...

?q=something
?version=1.0

**Comment by tveronezi** [comment]
@jeanouii This is a query parameter, right? That's not part of the path signature.

**Comment by tveronezi** [comment]
retest this please

**Comment by tbookless** [comment]
Just returned this to @tveronezi with some notes in the Jira

**Comment by tveronezi** [comment]
screen shot 2016-11-04 at 12 52 27 pm

**Comment by tbookless** [comment]
Not all cases covered, yet

**Comment by tbookless** [comment]
@jeanouii I have tested this locally and the issues that I identified are resolved. Please review and see if your issues are also resolved.

**Comment by tbookless** [comment]
fixes #171

**Comment by dblevins** [comment]
Instead of listing all rules when someone does one thing wrong, can we check each rule individually and only print the ones the user broke?

For example:

 - In code, check if the user used "//" 
 - Print, "Paths must not contain multiple "/" characters in a row"

**Comment by jeanouii** [comment]
@tbookless @tveronezi please see feedback on JIRA

**Comment by tveronezi** [comment]
@dblevins we could, but this is a complete refactor for what I implemented 16 days ago. 
Can we close this PR first and then create a new JIRA task?

**Comment by dblevins** [comment]
@tveronezi fine with me.  can you file that task?

**Comment by tveronezi** [comment]
https://tomitribe.atlassian.net/browse/REG-378

**Comment by tveronezi** [comment]
https://tomitribe.atlassian.net/browse/REG-379

**Comment by tveronezi** [comment]
https://tomitribe.atlassian.net/browse/REG-380

**Comment by jeanouii** [comment]
Thanks Thiago, we can let this one go.

**Comment by tbookless** [comment]
fixes #171

**Pull request merged**
