### PR TITLE
REG-346 #157 wait for scope value to be available before trying to list…

### PR DESCRIPTION
**Pull request by tveronezi**
…en to click event

### CODE REVIEW

**Comment by tbookless** [comment]
I was unable to repro this bug, and there are no steps provided. Please update the Jira with what happened and what was done.

**Comment by jeanouii** [comment]
retest this please

**Comment by tbookless** [comment]
Please see my request to update the Jira, above.

**Comment by jeanouii** [comment]
@tbookless this happened during the demo when I clicked on the button "show history".
I need to test locally without the fix again to make sure I can reproduce.

**Comment by jeanouii** [comment]
@tbookless see JIRA. I created an animated GIF to show you. Easy to reproduce locally as well.

**Comment by tbookless** [comment]
fixes #157

**Pull request merged**
