### PR TITLE
[WIP] REG-356 Home page - update h1, h2, h3, h4 sizing

### PR DESCRIPTION
**Pull request by Mummakill**
NodeArt team new guy

### CODE REVIEW

**Comment by Mummakill** [comment]
Rebased changes

**Comment by jeanouii** [comment]
retest this please

**Comment by tveronezi** [comment]
It looks weird.

screen shot 2016-11-10 at 1 13 13 pm

**Comment by tveronezi** [comment]
Current master looks like this...

screen shot 2016-11-10 at 1 15 15 pm

**Comment by tveronezi** [comment]
-1

**Comment by Mummakill** [comment]
Is endpoints must be H3, but with the same sizes as master?

**Comment by tbookless** [comment]
@Mummakill the colors changed in the text and the icons between the two screenshots that Thiago attached.

**Comment by Mummakill** [comment]
Fixed icons and colors. Please, check again!

**Pull request merged**
