### PR TITLE
REG-336 nodejs/npm versions updated

### PR DESCRIPTION
**Pull request by tveronezi**

### CODE REVIEW

**Comment by tveronezi** [comment]
retest this please

**Comment by jeanouii** [comment]
Back to you Thiago
Not sure why, but it still fails.

 41% 31/59 build modulesError: Missing binding /Users/jlmonteiro/devs/jeanouii/tomitribe/tribestream-api-registry/tribestream-api-registry-webapp/src/main/static/node_modules/node-sass/vendor/darwin-x64-48/binding.node
[ERROR] Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 6.x
[ERROR]
[ERROR] Found bindings for the following environments:
[ERROR]   - OS X 64-bit with Node.js 5.x
[ERROR]
[ERROR] This usually happens because your environment has changed since running `npm install`.
[ERROR] Run `npm rebuild node-sass` to build the binding for your current environment.
[ERROR]     at Object.<anonymous> (/Users/jlmonteiro/devs/jeanouii/tomitribe/tribestream-api-registry/tribestream-api-registry-webapp/src/main/static/node_modules/node-sass/lib/index.js:15:11)
[ERROR]     at Module._compile (module.js:570:32)
[ERROR]     at Object.Module._extensions..js (module.js:579:10)
[ERROR]     at Module.load (module.js:487:32)
[ERROR]     at tryModuleLoad (module.js:446:12)
[ERROR]     at Function.Module._load (module.js:438:3)
[ERROR]     at Module.require (module.js:497:17)
[ERROR]     at require (internal/module.js:20:19)
[ERROR]     at Object.<anonymous> (/Users/jlmonteiro/devs/jeanouii/tomitribe/tribestream-api-registry/tribestream-api-registry-webapp/src/main/static/node_modules/sass-loader/index.js:4:12)
[ERROR]     at Module._compile (module.js:570:32)
[ERROR]     at Object.Module._extensions..js (module.js:579:10)
[ERROR]     at Module.load (module.js:487:32)

Thanks in advance

**Comment by jeanouii** [comment]
image

Also works but had to merge the other PR into this one to test it

**Comment by tbookless** [comment]
fixes #122

**Pull request merged**
